
name: Build GT Neo 3 Kernel

on:
  workflow_dispatch:

jobs:
  build:
    name: Kernel Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3

      - name: Setup Proton Clang
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CLANG_PATH=$GITHUB_WORKSPACE/clang
          export KERNEL_DIR=$GITHUB_WORKSPACE
          export OUT=$KERNEL_DIR/out

          mkdir -p $OUT

          make O=$OUT vendor/lisaa_defconfig
          make -j$(nproc) O=$OUT             CC=$CLANG_PATH/bin/clang             CROSS_COMPILE=$CLANG_PATH/bin/aarch64-linux-gnu-             CLANG_TRIPLE=aarch64-linux-gnu-             LD=$CLANG_PATH/bin/ld.lld             AR=$CLANG_PATH/bin/llvm-ar             NM=$CLANG_PATH/bin/llvm-nm             OBJCOPY=$CLANG_PATH/bin/llvm-objcopy             OBJDUMP=$CLANG_PATH/bin/llvm-objdump             STRIP=$CLANG_PATH/bin/llvm-strip

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v3
        with:
          name: Image.gz-dtb
          path: out/arch/arm64/boot/Image.gz-dtb
